# Decision Tree

In [12]:
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn import preprocessing
from sklearn import tree

df = pd.read_csv('./house_data.csv')

y = df['建物單價元/坪']
X = df.drop(['建物單價元/坪'],axis=1)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = DecisionTreeRegressor(max_depth=6)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

# The mean squared error
print("Mean squared error: {}".format(mean_squared_error(y_test, y_pred)))
# Explained variance score: 1 is perfect prediction
print('R2 score: {}'.format(r2_score(y_test, y_pred)))

Mean squared error: 229.08793785921563
R2 score: 0.7155540426896219


In [11]:
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn import preprocessing
from sklearn import tree

df = pd.read_csv('./house_data.csv')

y = df['建物單價元/坪']
X = df.drop(['建物單價元/坪'],axis=1)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

scaler = preprocessing.StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)

model = DecisionTreeRegressor(max_depth=6)
model.fit(x_train, y_train)

x_test = scaler.transform(x_test)
y_pred = model.predict(x_test)

# The mean squared error
print("Mean squared error: {}".format(mean_squared_error(y_test, y_pred)))
# Explained variance score: 1 is perfect prediction
print('R2 score: {}'.format(r2_score(y_test, y_pred)))

Mean squared error: 242.63219049248673
R2 score: 0.7048881464619244


# Naive Bayes 

In [2]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB, MultinomialNB
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv('./house_data.csv')


y = df['建物單價元/坪']
X = df.drop(['建物單價元/坪'],axis=1)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = GaussianNB()
model.fit(X_train, y_train.astype('int'))


y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test.astype('int'), y_pred)
num_correct_samples = accuracy_score(y_test.astype('int'), y_pred, normalize=False)
con_matrix = confusion_matrix(y_test.astype('int'), y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('con_matrix: {}'.format(con_matrix))



number of correct sample: 314
accuracy: 0.007282510378736925
con_matrix: [[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
